# Generated by Django 5.0.7 on 2024-09-08 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_rename_compradetalles_compradetalle'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=30, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updater', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('deleter', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=30, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updater', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('deleter', models.CharField(blank=True, max_length=30, null=True)),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_esperado', models.DateField()),
                ('valor_esperado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_recibido', models.DateField()),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_recibido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recibido_por', models.CharField(blank=True, max_length=30, null=True)),
                ('nota', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compras.estadopedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['id'],
            },
        ),
    ]
